server:
  port: 8087
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

